import os
PROJ = os.environ.get("BLANKET_PROJ", os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
SRC_PHOTO = os.path.join(PROJ, "reference", "blanket-2026-09-13.jpeg")
SRC_ESTIMATES = os.path.join(PROJ, "reference", "italy-region-hex-counts.json")
import numpy as np, json, collections
COLS,ROWS=72,90
cells=np.load("cells_clean.npy"); sewn=np.load("sewn_clean.npy")
REGJ=json.load(open(SRC_ESTIMATES))["regions"]
names=[r["region"] for r in REGJ]
photo_cols=json.load(open("regioncolours.json"))["colours"]

MISS_ROWS=34
LEFT_COLS=(0,5); RIGHT_COLS=(COLS-8,COLS-1)
def idx(r,c): return r*COLS+c

def order_for(c0,c1,inner_first_from):
    """bottom row upward; within a row, from the column nearest the map outward."""
    out=[]
    cols=list(range(c0,c1+1))
    cols=cols if inner_first_from=="left" else cols          # placeholder
    for r in range(MISS_ROWS-1,-1,-1):
        for c in cols:
            out.append(idx(r,c))
    return out
left_cols=list(range(LEFT_COLS[0],LEFT_COLS[1]+1))[::-1]      # inner (col 5) -> edge (col 0)
right_cols=list(range(RIGHT_COLS[0],RIGHT_COLS[1]+1))         # inner (col 64) -> edge (col 71)
def build(cols):
    out=[]
    for r in range(MISS_ROWS-1,-1,-1):
        for c in cols: out.append(idx(r,c))
    return out
left_order=build(left_cols); right_order=build(right_cols)
assert len(left_order)==6*MISS_ROWS and len(right_order)==8*MISS_ROWS

cnt=collections.Counter(cells.ravel().tolist())
regions=[]
for k,n in enumerate(names,1):
    r=REGJ[k-1]
    regions.append({"id":k,"name":n,"colour":r["colour"],"colourFromPhoto":photo_cols[k-1],
                    "count":int(cnt[k]),"priorEstimate":r["estimate"],
                    "priorRange":[r["low"],r["high"]]})
mapTotal=sum(x["count"] for x in regions)
oceanTotal=COLS*ROWS-mapTotal

data={
 "_readme":"Generated by tools/fit-grid from reference/blanket-2026-09-13.jpeg. See FINDINGS.md. Every number that may change lives in `config`.",
 "config":{
   "grid":{"cols":COLS,"rows":ROWS},
   "total":COLS*ROWS,
   "orientation":"flat-top hexagons; odd-indexed columns sit half a row higher (column 0 is the low one). cells[] is row-major: index = row*cols + col.",
   "startDate":"2025-07-01",
   "startDateConfirmed":False,
   "deadline":"2027-01-01",
   "deadlineConfirmed":False,
   "targetPerWeek":88,
   "oceanColour":"#2c3a4e",
   "oceanName":"Ocean",
   "patch":{"rowsHigh":10,"leftAcross":6,"rightAcross":8}
 },
 "provenance":{
   "gridSource":"Fitted to the 13 Sep 2026 photo: blanket outline segmented from the floor, four boundary lines fitted, homography to a 72x90 flat-top lattice, cells classified by colour. Lattice/colour agreement 99.4%.",
   "estimatesNote":"regions[].priorEstimate is the earlier per-region estimate from the 20 Sep close-up. Every region came out about 2.4x higher when counted on the fitted grid; see FINDINGS.md.",
   "counted":{"map":mapTotal,"ocean":oceanTotal,"total":COLS*ROWS}
 },
 "regions":regions,
 "cells":cells.ravel().astype(int).tolist(),
 "missing":{
  "left":{"label":"Left, the Sardinia side","across":6,"high":10,
          "cols":list(LEFT_COLS),"rows":[0,MISS_ROWS-1],
          "count":6*MISS_ROWS,"perPatch":60,"order":left_order},
  "right":{"label":"Right, the Puglia side","across":8,"high":10,
           "cols":list(RIGHT_COLS),"rows":[0,MISS_ROWS-1],
           "count":8*MISS_ROWS,"perPatch":80,"order":right_order}
 },
 "stages":[
   {"date":"2026-09-13","photo":"photos/2026-09-13.jpg","thumb":"photos/thumbs/2026-09-13.jpg",
    "sewnLeft":0,"sewnRight":0,
    "note":"Whole-blanket photo. Both corner blocks entirely unsewn; counts read off this photo."},
   {"date":"2026-09-20","photo":None,"thumb":None,"sewnLeft":None,"sewnRight":None,
    "note":"Close-up photo referenced in the brief but not supplied. Add it with `npm run add-stage`."}
 ]
}
out=os.path.join(PROJ,"data","blanket.json")
json.dump(data,open(out,"w"),separators=(",",":"))
import os
print("wrote",out,os.path.getsize(out),"bytes")
print("map",mapTotal,"ocean",oceanTotal,"missing left",6*MISS_ROWS,"right",8*MISS_ROWS,"total missing",14*MISS_ROWS)
